# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  caddy:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}-caddy.loadbalancer.server.port=80'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-caddy.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)'
    networks:
      default: {}
      traefik: {}

  mailhog:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}-mailhog.loadbalancer.server.port=8025'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailhog.rule=Host(`mail.${COMPOSE_PROJECT_NAME}.localhost`)'
    networks:
      default: {}
      traefik: {}

  buggregator:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}-buggregator.loadbalancer.server.port=8000'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}-buggregator.rule=Host(`buggregator.${COMPOSE_PROJECT_NAME}.localhost`)'
    networks:
      default: {}
      traefik: {}

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik}
